services:
  - type: web
    name: clipcut
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PADDLE_CLIENT_TOKEN
        sync: false
      - key: PADDLE_WEBHOOK_SECRET
        sync: false
      - key: PADDLE_PRO_PRICE_ID
        sync: false
      - key: PADDLE_PRO_YEARLY_PRICE_ID
        sync: false
      - key: PADDLE_CREATOR_PRICE_ID
        sync: false
      - key: PADDLE_CREATOR_YEARLY_PRICE_ID
        sync: false
      - key: PADDLE_BIZ_PRICE_ID
        sync: false
      - key: PADDLE_BIZ_YEARLY_PRICE_ID
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
