services:
  - type: web
    name: clipcut
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_PRO_YEARLY_PRICE_ID
        sync: false
      - key: STRIPE_CREATOR_PRICE_ID
        sync: false
      - key: STRIPE_CREATOR_YEARLY_PRICE_ID
        sync: false
      - key: STRIPE_BIZ_PRICE_ID
        sync: false
      - key: STRIPE_BIZ_YEARLY_PRICE_ID
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
